apiVersion: v1
kind: Service
metadata:
  name: account-interface
spec:
  selector:
    app: account-interface
  ports:
    - name: http
      port: 6060
      protocol: TCP
      targetPort: 6060
      nodePort: 30001
  type: NodePort
