apiVersion: v1
kind: Service
metadata:
  name: http-gateway
spec:
  selector:
    app: http-gateway
  ports:
    - name: http
      port: 2233
      protocol: TCP
      targetPort: 2233
      nodePort: 30000
  type: NodePort
