apiVersion: v1
kind: Service
metadata:
  name: account-interface
spec:
  selector:
    app: account-interface
  ports:
    - name: http
      port: 2233
      protocol: TCP
      targetPort: 2233
      nodePort: 30000
  type: NodePort
