apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-gateway
  name: http-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-gateway
  template:
    metadata:
      labels:
        app: http-gateway
    spec:
      hostAliases:
      - ip: "192.168.64.1"
        hostnames:
          - "host.minikube.internal"
      containers:
        - name: http-gateway
          env:
            - name: node_name
              valueFrom:
               fieldRef:
                  fieldPath: spec.nodeName
            - name: node_ip
              valueFrom:
               fieldRef:
                  fieldPath: status.hostIP
            - name: pod_name
              valueFrom:
               fieldRef:
                 fieldPath: metadata.name
            - name: pod_ip
              valueFrom:
               fieldRef:
                  fieldPath: status.podIP
            - name: namespace
              valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
          image: thrc/http-gateway:v1
          ports:
            - containerPort: 6060
