apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service    
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      hostAliases:
      - ip: "192.168.64.1"
        hostnames:
          - "host.minikube.internal"
      containers:
        - name: user-service
          env:
            - name: node_name
              valueFrom:
               fieldRef:
                  fieldPath: spec.nodeName
            - name: node_ip
              valueFrom:
               fieldRef:
                  fieldPath: status.hostIP
            - name: pod_name
              valueFrom:
               fieldRef:
                 fieldPath: metadata.name
            - name: pod_ip
              valueFrom:
               fieldRef:
                  fieldPath: status.podIP
            - name: namespace
              valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
          image: thrc/user-service:v1
          ports:
            - containerPort: 9091
